# Generated by Django 6.0.5 on 2026-06-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fragment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="content/fragments/", verbose_name="图片"
                    ),
                ),
                (
                    "shot_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="拍摄时间"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="地点标签"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "照片碎片",
                "verbose_name_plural": "照片碎片",
                "ordering": ["-shot_at", "-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MediaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("creator", models.CharField(max_length=200, verbose_name="作者/导演")),
                (
                    "category",
                    models.CharField(
                        choices=[("music", "Music"), ("films", "Films")],
                        max_length=20,
                        verbose_name="类别",
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        upload_to="content/media_items/covers/", verbose_name="封面图片"
                    ),
                ),
                ("summary", models.TextField(verbose_name="核心介绍")),
                ("body", models.TextField(blank=True, verbose_name="详细文本")),
                ("external_url", models.URLField(blank=True, verbose_name="外部链接")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "媒体条目",
                "verbose_name_plural": "媒体条目",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                (
                    "summary",
                    models.CharField(blank=True, max_length=255, verbose_name="摘要"),
                ),
                ("body", models.TextField(verbose_name="正文")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "文章",
                "verbose_name_plural": "文章",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
