# Generated by Django 6.0.5 on 2026-06-18 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fragment",
            options={
                "ordering": ["-shot_at", "-created_at", "-id"],
                "verbose_name": "照片墙",
                "verbose_name_plural": "照片墙",
            },
        ),
        migrations.AlterModelOptions(
            name="mediaitem",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "音乐/电影",
                "verbose_name_plural": "音乐/电影",
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "博客",
                "verbose_name_plural": "博客",
            },
        ),
    ]
