# Generated by Django 6.0.5 on 2026-06-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_rename_admin_labels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediaitem",
            name="creator",
            field=models.CharField(max_length=200, verbose_name="艺术家"),
        ),
        migrations.AlterField(
            model_name="mediaitem",
            name="summary",
            field=models.TextField(verbose_name="简介"),
        ),
    ]
