# Generated by Django 6.0.6 on 2026-06-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_rename_media_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "home_background",
                    models.ImageField(
                        blank=True,
                        upload_to="content/site_profile/home/",
                        verbose_name="首页背景图",
                    ),
                ),
                (
                    "welcome_message",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="欢迎语"
                    ),
                ),
                (
                    "quote",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Quote"
                    ),
                ),
                (
                    "about_nickname",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="About 昵称",
                    ),
                ),
                (
                    "about_bio",
                    models.TextField(blank=True, default="", verbose_name="About 简介"),
                ),
                (
                    "about_avatar",
                    models.ImageField(
                        blank=True,
                        upload_to="content/site_profile/about/",
                        verbose_name="About 头像",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "站点资料",
                "verbose_name_plural": "站点资料",
                "ordering": ["-updated_at", "-id"],
            },
        ),
    ]
