# Generated by Django 6.0.6 on 2026-06-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_siteprofile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="siteprofile",
            options={
                "ordering": ["-updated_at", "-id"],
                "verbose_name": "首页与个人资料",
                "verbose_name_plural": "首页与个人资料",
            },
        ),
        migrations.AlterField(
            model_name="mediaitem",
            name="body",
            field=models.TextField(blank=True, verbose_name="更多内容"),
        ),
        migrations.AlterField(
            model_name="mediaitem",
            name="cover",
            field=models.ImageField(
                upload_to="content/media_items/covers/", verbose_name="图片"
            ),
        ),
        migrations.AlterField(
            model_name="siteprofile",
            name="about_avatar",
            field=models.ImageField(
                blank=True,
                upload_to="content/site_profile/about/",
                verbose_name="个人资料头像",
            ),
        ),
        migrations.AlterField(
            model_name="siteprofile",
            name="about_bio",
            field=models.TextField(blank=True, default="", verbose_name="个人资料简介"),
        ),
        migrations.AlterField(
            model_name="siteprofile",
            name="about_nickname",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="个人资料昵称"
            ),
        ),
    ]
