# Generated by Django 6.0.5 on 2026-06-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_alter_siteprofile_options_alter_mediaitem_body_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siteprofile",
            name="quote",
        ),
        migrations.RemoveField(
            model_name="siteprofile",
            name="welcome_message",
        ),
        migrations.AddField(
            model_name="fragment",
            name="people_info",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="人物信息"
            ),
        ),
        migrations.AddField(
            model_name="fragment",
            name="summary",
            field=models.TextField(blank=True, default="", verbose_name="简介"),
        ),
        migrations.AddField(
            model_name="fragment",
            name="title",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="名称"
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="about_name",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="个人资料名字"
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="about_region",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="个人资料地区"
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="elsewhere_bilibili_label",
            field=models.CharField(
                blank=True,
                default="Bilibili",
                max_length=100,
                verbose_name="Elsewhere - Bilibili 名称",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="elsewhere_bilibili_url",
            field=models.URLField(
                blank=True, default="", verbose_name="Elsewhere - Bilibili 链接"
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="elsewhere_email_label",
            field=models.CharField(
                blank=True,
                default="Email",
                max_length=100,
                verbose_name="Elsewhere - Email 名称",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="elsewhere_email_url",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Elsewhere - Email 链接",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="elsewhere_github_label",
            field=models.CharField(
                blank=True,
                default="GitHub",
                max_length=100,
                verbose_name="Elsewhere - GitHub 名称",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="elsewhere_github_url",
            field=models.URLField(
                blank=True, default="", verbose_name="Elsewhere - GitHub 链接"
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="elsewhere_netease_label",
            field=models.CharField(
                blank=True,
                default="网易云音乐",
                max_length=100,
                verbose_name="Elsewhere - 网易云 名称",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="elsewhere_netease_url",
            field=models.URLField(
                blank=True, default="", verbose_name="Elsewhere - 网易云 链接"
            ),
        ),
    ]
