# Generated by Django 6.0.5 on 2026-06-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_remove_siteprofile_quote_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaitem",
            name="release_year",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="发行年份"
            ),
        ),
    ]
